services:
  geodb:
    image: 'postgis/postgis:15-3.4'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./geodb/persistence:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
