#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# API
npx concurrently "npm:test --prefix api" "npm:format --prefix api" "npm:lint --prefix api"

# ETL
# if [ -d etl/venv ] 
# then
#     source etl/venv/bin/activate
#     black etl/*.ipynb
#     deactivate
# else
#     echo "ETL venv not found. Skipping formatting."
# fi
